export { BERO, MAX_NUMBER_OF_PLAYERS, MIN_NUMBER_OF_PLAYERS, POKERTH_VERSION_MAJOR, POKERTH_VERSION_MINOR, POKERTH_VERSION_PATCH, POKERTH_BETA_RELEASE_STRING, CLIENT_TYPE_QT_WIDGET, AVATAR_SERVER_URL, WEBSOCKET_URL } from './gameDefs.js'
export * from './protocol.js'
